DROP TABLE IF EXISTS theorems;
DROP TABLE IF EXISTS mathematicians;
DROP TABLE IF EXISTS proof_techniques;
DROP TABLE IF EXISTS famous_numbers;
DROP TABLE IF EXISTS paradoxes;

CREATE TABLE theorems (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  url TEXT NOT NULL
);

CREATE TABLE mathematicians (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  url TEXT NOT NULL
);

CREATE TABLE proof_techniques (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  url TEXT NOT NULL
);

CREATE TABLE famous_numbers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  url TEXT NOT NULL
);

CREATE TABLE paradoxes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  url TEXT NOT NULL
);
